FROM node:20-slim

# Instalar bibliotecas comunes
RUN npm install -g \
    axios@1.6.5 \
    lodash@4.17.21 \
    moment@2.30.1

# Usuario sin privilegios (Node ya tiene user node con UID 1000)
RUN mkdir /code && \
    chown node:node /code

USER node
WORKDIR /code

# Script por defecto
CMD ["node", "script.js"]
